services:
  postgres:
    image: postgres:16
    container_name: crudjava-postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 13371337
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:4.1.2-management
    container_name: crudjava-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:8-alpine
    container_name: crudjava-redis
    ports:
      - "6380:6379"

  app:
    build: .
    container_name: crudjava-app
    depends_on:
      - postgres
      - rabbitmq
      - redis
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

volumes:
  postgres_data:
